# Generated by Django 4.2.1 on 2024-05-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersconfig',
            name='otp',
            field=models.CharField(max_length=6, blank=True, null=True),  # New field for OTP
        ),
        migrations.AddField(
            model_name='usersconfig',
            name='otp_verification',
            field=models.BooleanField(default=False),  # OTP verification status
        ),
        migrations.AddField(
            model_name='usersconfig',
            name='otp_expire',
            field=models.DateTimeField(blank=True, null=True),  # OTP expiration datetime
        ),
    ]
