# Generated by Django 4.2.1 on 2024-05-08 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_changed_users_config'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersconfig',
            options={'verbose_name_plural': 'Users Configuration'},
        ),
    ]
