# Generated by Django 4.2.1 on 2024-05-08 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_usersconfig_options'),
        ('examquestions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Start_exam_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.usersconfig')),
            ],
        ),
        migrations.CreateModel(
            name='ExamName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('questions', models.ManyToManyField(to='examquestions.question')),
            ],
        ),
        migrations.AlterField(
            model_name='attemptedquestion',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examquestions.examname'),
        ),
        migrations.AlterField(
            model_name='result',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='examquestions.examname'),
        ),
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
