# Generated by Django 4.2.1 on 2024-05-09 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('examquestions', '0003_start_exam_user_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='start_exam_user',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='examquestions.examname'),
            preserve_default=False,
        ),
    ]
