# Generated by Django 4.2.1 on 2024-05-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examquestions', '0004_start_exam_user_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='start_exam_user',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
